apps/dashboard/urls.py
from django.urls import path
from apps.dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.inicio, name="inicio"),
]

apps/roles/urls.py
from django.urls import path
from apps.roles import views

app_name = 'roles'

urlpatterns = [
    path('', views.roles, name="roles"),
    path('eliminar_roles/<int:pk_id>/', views.eliminar_roles, name='eliminar_roles'),
    path('registrar_roles/', views.registrar_roles, name='registrar_roles'),
    path('editar_roles/<int:pk_id>/', views.editar_roles, name="editar_roles"),
    path('permiso_roles/<int:pk_id>/', views.permiso_roles, name="permiso_roles"),
]

proyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('', include('apps.dashboard.urls')),
    path('authentication/', include('apps.authentication.urls')),
    path('empresa/', include('apps.empresa.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('roles/', include('apps.roles.urls')),
    path('productos/', include('apps.articulos.urls')),
    path('categorias/', include('apps.categorias.urls')),
    path('lotes/', include('apps.lotes.urls')),
    path('compras/', include('apps.compras.urls')),
    path('ventas/', include('apps.ventas.urls')),
    path('proveedores/', include('apps.proveedores.urls')),
    path('clientes/', include('apps.clientes.urls')),
    path('reportes/', include('apps.informe.urls')),
    path('notificaciones/', include('apps.notificaciones.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/roles/models.py
from django.db import models

# Create your models here.

apps/roles/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import Group, Permission
from django import forms

# Clase Formulario Grupo (roles)
class GroupForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'placeholder': 'Ingresa el nombre'})

    class Meta:
        model = Group
        fields = ['name']
        #widgets = {'permissions': forms.CheckboxSelectMultiple}


# Clase Formulario Permiso (permisos de usuarios en roles)
class PermisoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PermisoForm, self).__init__(*args, **kwargs)
        
        # Filtrar los permisos
        permisos_filtrados = Permission.objects.filter(id__gte=97).order_by('id') # Filtrar los permisos con ID mayor
        choices = [(permiso.id, permiso.name) for permiso in permisos_filtrados]  # Crea una lista de tuplas (valor, etiqueta)
        self.fields['permissions'].queryset = permisos_filtrados
        self.fields['permissions'].choices = choices

    class Meta:
        model = Group
        fields = ['permissions']
        widgets = {'permissions': forms.CheckboxSelectMultiple(
                attrs={'class': 'custom-control-input'}
            )
        }
    

apps/roles/views.py
from django.shortcuts import render, redirect, render
from django.contrib.auth.decorators import login_required, permission_required
from apps.roles.forms import GroupForm, PermisoForm
from django.contrib import messages
from django.contrib.auth.models import Group

# Vista lista de Roles
@login_required
@permission_required('usuarios.ver_roles', raise_exception=True)
def roles(request):
    roles = Group.objects.all().order_by('name')
    return render(request, 'roles.html', {"roles": roles})

# Vista Eliminación de Rol
@login_required
@permission_required('usuarios.eliminar_roles', raise_exception=True)
def eliminar_roles(request, pk_id):
    Group.objects.get(pk=pk_id).delete()
    messages.success(request, "¡Rol Eliminado Correctamente!")
    return redirect('roles:roles')

# Vista Registro de Rol
@login_required
@permission_required('usuarios.crear_roles', raise_exception=True)
def registrar_roles(request):
    form = GroupForm()
    if request.method == 'POST':
        form = GroupForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, "¡Registro de Rol Exitoso!")
            return redirect('roles:roles')
    
    return render(request, 'registrar_roles.html', {'form': form})

# Vista Edición de Rol
@login_required
@permission_required('usuarios.editar_roles', raise_exception=True)
def editar_roles(request, pk_id):
    rol = Group.objects.get(pk=pk_id)
    form = GroupForm(instance=rol)
    if request.method=="POST":
        form = GroupForm(request.POST, instance=rol)
        form.save()
        messages.success(request, "¡Rol Modificado Correctamente!")
        return redirect("roles:roles")
    
    return render(request, 'editar_roles.html', {"form":form, 'pk':pk_id})

# Vista Asignación de Permisos a Rol
@login_required
@permission_required('usuarios.asignar_permisos_roles', raise_exception=True)
def permiso_roles(request, pk_id):
    permiso_grupo = Group.objects.get(pk=pk_id)
    form = PermisoForm(instance=permiso_grupo)
    if request.method == "POST":
        form = PermisoForm(request.POST, instance=permiso_grupo)
        
        if form.is_valid():
            form.save()
            
            # Asignar permisos directamente al usuario
            for usuario in permiso_grupo.user_set.all():
                usuario.user_permissions.set(form.cleaned_data['permissions'])
            messages.success(request, "¡Permisos del Rol Modificados Correctamente!")
            return redirect("roles:roles")
    
    return render(request, 'permiso_roles.html', {"form": form, 'pk': pk_id})

apps/roles/templates/editar_roles.html
<div class="modal-dialog modal-custom-width" role="document">
    <div class="modal-content border-0 shadow-lg">
        <div class="modal-header bg-light">
            <h5 class="modal-title text-dark font-weight-bold">
                <i class="fas fa-edit text-primary mr-2"></i>Editar Rol
            </h5>
            <button class="close" type="button" data-dismiss="modal" area-label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% load crispy_forms_tags %}
                <form method="POST" action="{% url 'roles:editar_roles' pk %}">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-sm btn-primary" id="botonModificar">
                            <i class="fas fa-save"></i> Guardar
                        </button>
                        <button type="reset" class="btn btn-sm btn-warning ml-2">
                            <i class="fas fa-undo"></i> Deshacer
                        </button>  
                    </div>
                </form>
        </div>
    </div>
</div>

apps/roles/templates/permiso_roles.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content border-0 shadow-lg">
        <div class="modal-header bg-light">
            <h5 class="modal-title text-dark font-weight-bold">
                <i class="fas fa-key text-primary mr-2"></i>Control de Acceso
            </h5>
            <button class="close" type="button" data-dismiss="modal" area-label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% load crispy_forms_tags %}
            <form method="POST" action="{% url 'roles:permiso_roles' pk %}">
                {% csrf_token %}
                {{ form.non_field_errors }}
                
                <!-- Sección de permisos organizados en columnas -->
                <div class="form-group">
                    <div class="row">
                        <!-- Columna de permisos "Ver" -->
                        <div class="col-md-4 mb-2">
                            <div class="d-flex align-items-center">
                                <div class="custom-control custom-switch mr-1">
                                    <input type="checkbox" class="custom-control-input" id="checkAllVer">
                                    <label class="custom-control-label" for="checkAllVer">
                                        <h5 class="h6 font-weight-bold text-dark"><i class="fas fa-sm fa-eye mr-1"></i>Ver</h5>
                                    </label>
                                </div>
                            </div>
                            {% for checkbox in form.permissions %}
                                {% if 'ver' in checkbox.choice_label|lower %}
                                    <div class="custom-control custom-switch">
                                        {{ checkbox.tag }}
                                        <label class="custom-control-label" for="{{ checkbox.id_for_label }}">{{ checkbox.choice_label }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        
                        <!-- Columna de permisos "Crear" -->
                        <div class="col-md-4 mb-2">
                            <div class="d-flex align-items-center">
                                <div class="custom-control custom-switch mr-1">
                                    <input type="checkbox" class="custom-control-input" id="checkAllCrear">
                                    <label class="custom-control-label" for="checkAllCrear">
                                        <h5 class="h6 font-weight-bold text-dark"><i class="fas fa-sm fa-plus-circle mr-1"></i>Crear</h5>
                                    </label>
                                </div>
                            </div>
                            {% for checkbox in form.permissions %}
                                {% if 'crear' in checkbox.choice_label|lower %}
                                    <div class="custom-control custom-switch">
                                        {{ checkbox.tag }}
                                        <label class="custom-control-label" for="{{ checkbox.id_for_label }}">{{ checkbox.choice_label }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                        <!-- Columna de permisos "Editar" -->
                        <div class="col-md-4 mb-2">
                            <div class="d-flex align-items-center">
                                <div class="custom-control custom-switch mr-1">
                                    <input type="checkbox" class="custom-control-input" id="checkAllEditar">
                                    <label class="custom-control-label" for="checkAllEditar">
                                        <h5 class="h6 font-weight-bold text-dark"><i class="fas fa-sm fa-edit mr-1"></i>Editar</h5>
                                    </label>
                                </div>
                            </div>
                            {% for checkbox in form.permissions %}
                                {% if 'editar' in checkbox.choice_label|lower %}
                                    <div class="custom-control custom-switch">
                                        {{ checkbox.tag }}
                                        <label class="custom-control-label" for="{{ checkbox.id_for_label }}">{{ checkbox.choice_label }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                        <!-- Columna de permisos "Eliminar" -->
                        <div class="col-md-4">
                            <div class="d-flex align-items-center">
                                <div class="custom-control custom-switch mr-1">
                                    <input type="checkbox" class="custom-control-input" id="checkAllEliminar">
                                    <label class="custom-control-label" for="checkAllEliminar">
                                        <h5 class="h6 font-weight-bold text-dark"><i class="fas fa-sm fa-trash-alt mr-1"></i>Eliminar</h5>
                                    </label>
                                </div>
                            </div>
                            {% for checkbox in form.permissions %}
                                {% if 'eliminar' in checkbox.choice_label|lower %}
                                    <div class="custom-control custom-switch">
                                        {{ checkbox.tag }}
                                        <label class="custom-control-label" for="{{ checkbox.id_for_label }}">{{ checkbox.choice_label }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                        <!-- Columna de permisos "Otros" -->
                        <div class="col-md-4">
                            <div class="d-flex align-items-center">
                                <div class="custom-control custom-switch mr-1">
                                    <input type="checkbox" class="custom-control-input" id="checkAllOtros">
                                    <label class="custom-control-label" for="checkAllOtros">
                                        <h5 class="h6 font-weight-bold text-dark"><i class="fas fa-sm fa-cogs mr-1"></i>Otros</h5>
                                    </label>
                                </div>
                            </div>
                            {% for checkbox in form.permissions %}
                                {% if 'asignar' in checkbox.choice_label|lower or 'generar' in checkbox.choice_label|lower or 'config' in checkbox.choice_label|lower %}
                                    <div class="custom-control custom-switch">
                                        {{ checkbox.tag }}
                                        <label class="custom-control-label" for="{{ checkbox.id_for_label }}">{{ checkbox.choice_label }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                
                <!-- Botones -->
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-sm btn-primary" id="botonModificar">
                        <i class="fas fa-save"></i> Guardar
                    </button>
                    <button type="reset" class="btn btn-sm btn-warning ml-2">
                        <i class="fas fa-undo"></i> Deshacer
                    </button>  
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Seleccionar todas -->
<script>
    $(document).ready(function() {
        const divs = document.querySelectorAll('.custom-switch');
        let allCheckedver = true;
        let allCheckedcrear = true;
        let allCheckededitar = true;
        let allCheckedeliminar = true;
        let allCheckedotros = true;

        divs.forEach(div => {
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('ver ')) {
                console.log(div.querySelector('.custom-control-label'));
                if (!div.querySelector('input[type="checkbox"]').checked) {
                    allCheckedver = false;
                }
            }
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('crear ')) {
                if (!div.querySelector('input[type="checkbox"]').checked) {
                    allCheckedcrear = false;
                }
            }
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('editar ')) {
                if (!div.querySelector('input[type="checkbox"]').checked) {
                    allCheckededitar = false;
                }
            }
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('eliminar ')) {
                if (!div.querySelector('input[type="checkbox"]').checked) {
                    allCheckedeliminar = false;
                }
            }
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('asignar ') || 
                div.querySelector('.custom-control-label').textContent.toLowerCase().includes('generar ') ||
                div.querySelector('.custom-control-label').textContent.toLowerCase().includes('config')) {
                if (!div.querySelector('input[type="checkbox"]').checked) {
                    allCheckedotros = false;
                }
            }
        });
        if (allCheckedver) {
            document.getElementById('checkAllVer').checked = true;
        }
        if (allCheckedcrear) {
            document.getElementById('checkAllCrear').checked = true;
        }
        if (allCheckededitar) {
            document.getElementById('checkAllEditar').checked = true;
        }
        if (allCheckedeliminar) {
            document.getElementById('checkAllEliminar').checked = true;
        }
        if (allCheckedotros) {
            document.getElementById('checkAllOtros').checked = true;
        }
    });
    
    document.getElementById('checkAllVer').addEventListener('change', function() {
        const divs = document.querySelectorAll('.custom-switch');
        divs.forEach(div => {
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('ver ')) {
                div.querySelector('input[type="checkbox"]').checked = this.checked;
            }
        });
    });
    document.getElementById('checkAllCrear').addEventListener('change', function() {
        const divs = document.querySelectorAll('.custom-switch');
        divs.forEach(div => {
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('crear ')) {
                div.querySelector('input[type="checkbox"]').checked = this.checked;
            }
        });
    });
    document.getElementById('checkAllEditar').addEventListener('change', function() {
        const divs = document.querySelectorAll('.custom-switch');
        divs.forEach(div => {
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('editar ')) {
                div.querySelector('input[type="checkbox"]').checked = this.checked;
            }
        });
    });
    document.getElementById('checkAllEliminar').addEventListener('change', function() {
        const divs = document.querySelectorAll('.custom-switch');
        divs.forEach(div => {
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('eliminar ')) {
                div.querySelector('input[type="checkbox"]').checked = this.checked;
            }
        });
    });
    document.getElementById('checkAllOtros').addEventListener('change', function() {
        const divs = document.querySelectorAll('.custom-switch');
        divs.forEach(div => {
            if (div.querySelector('.custom-control-label').textContent.toLowerCase().includes('asignar ') || 
            div.querySelector('.custom-control-label').textContent.toLowerCase().includes('generar ') ||
            div.querySelector('.custom-control-label').textContent.toLowerCase().includes('config')) {
                div.querySelector('input[type="checkbox"]').checked = this.checked;
            }
        });
    });
</script>

apps/roles/templates/registrar_roles.html
<div class="modal-dialog modal-custom-width" role="document">
   <div class="modal-content border-0 shadow-lg">
        <div class="modal-header bg-light">
            <h5 class="modal-title text-dark font-weight-bold">
                <i class="fas fa-edit text-primary mr-2"></i>Nuevo Rol
            </h5>
            <button class="close" type="button" data-dismiss="modal" area-label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% load crispy_forms_tags %}
                <form method="POST" action="{% url 'roles:registrar_roles' %}">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-sm btn-primary">
                            <i class="fas fa-save"></i> Guardar
                        </button>
                        <button type="reset" class="btn btn-sm btn-warning ml-2">
                            <i class="fas fa-eraser"></i> Limpiar
                        </button>  
                    </div>
                </form>
        </div>
    </div>
</div>

apps/roles/templates/roles.html
{% extends "inventario_principal/base.html" %}

{% block titulo %}Listado de Roles{% endblock titulo %}

{% block contenido %}
    <!-- Page Heading -->
    <div class="mb-4">
        <h1 class="h3 mb-0 text-gray-800">Roles de Usuarios</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb" style="background-color: transparent; padding: 0; margin: 0;">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:inicio' %}"><i class="fas fa-home mr-2"></i>Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Roles</li>
            </ol>
        </nav>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header d-flex justify-content-between align-items-center card-csslist">
            <h6 class="m-0 font-weight-bold text-primary h5"><i class="fas fa-user-tag mr-2"></i>Gestión de Roles</h6>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-between mb-3">
                <!-- Espacio separador (puedes ajustar el tamaño según tus preferencias) -->
                <div style="width: 20px;"></div>
        
                <!-- Botón "Nuevo" con la clase ml-auto para alinear a la derecha -->
                {% if perms.usuarios.crear_roles %}
                    <button onclick="abrir_modal_nuevo('{% url 'roles:registrar_roles' %}')" class="btn btn-sm btn-primary rounded-pill ml-auto">
                        <i class="fas fa-plus-circle"></i> Registrar Rol
                    </button>
                {% endif %}
            </div>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Puedes agregar o quitar filas según tus necesidades -->
                        {% if roles %}
                            {% for rol in roles %}
                                <tr>
                                    <td>{{ rol.name }}</td>
                                        <td class="text-center">
                                            <div class="d-flex">
                                                <!-- Botón para Otorgar Permisos -->
                                                {% if perms.usuarios.asignar_permisos_roles %}
                                                <button type="button" class="btn btn-secondary btn-sm mr-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Otorgar Permisos" onclick="abrir_modal_permiso('{% url 'roles:permiso_roles' rol.pk %}')">
                                                    <i class="fas fa-key fa-sm"></i>
                                                </button>
                                                {% endif %}
                                                <!-- Botón para Editar -->
                                                {% if perms.usuarios.editar_roles %}
                                                <button type="button" class="btn btn-warning btn-sm mr-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar" onclick="abrir_modal_editar('{% url 'roles:editar_roles' rol.pk %}')">
                                                    <i class="fas fa-edit fa-sm"></i>
                                                </button>
                                                {% endif %}
                                                <!-- Botón para Eliminar -->
                                                {% if perms.usuarios.eliminar_roles %}
                                                <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar" onclick="Eliminar_Rol({{rol.pk}})">
                                                    <i class="fas fa-trash-alt fa-sm"></i>
                                                </button>
                                                {% endif %}
                                            </div>
                                        </td>                                             
                                </tr>
                            {% endfor %}
                        {% endif %}
                        <!-- ... -->
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <!-- Modal nuevo -->
    <div class="modal fade" id="nuevo" role="dialog">
    </div>
    <!-- Modal editar -->
    <div class="modal fade" id="editar" role="dialog">
    </div>
    <!-- Modal permiso -->
    <div class="modal fade" id="permiso" role="dialog">
    </div>
{% endblock contenido %}

{% block script %}
    <!-- SweetAlert para confirmar la eliminación -->
    <script>
        function Eliminar_Rol(id){
            Swal.fire({
                title: "¿Estás seguro de eliminar?",
                text: `Esta acción no se puede deshacer. Los usuarios asociados a este rol se quedarán sin este rol.`,
                icon: "warning",
                showCancelButton: true,
                confirmButtonText: "Aceptar",
                cancelButtonText: "Cancelar",
                confirmButtonColor: "#4169E1"
            })
            .then(function(result){
                if(result.isConfirmed){
                    window.location.href = "/roles/eliminar_roles/"+id+"/"
                }
            })
        }
    </script>

    <!-- Abrir Modal nuevo -->
    <script type="text/javascript">
        var $ =jQuery.noConflict();
        function abrir_modal_nuevo(url){
            $('#nuevo').load(url, function(){
                $(this).modal('show');
            })
        }
    </script>

    <!-- Abrir Modal editar -->
    <script type="text/javascript">
        var $ =jQuery.noConflict();
        function abrir_modal_editar(url){
            $('#editar').load(url, function(){
                $(this).modal('show');
            })
        }
    </script>

    <!-- Abrir Modal editar permisos -->
    <script type="text/javascript">
        var $ =jQuery.noConflict();
        function abrir_modal_permiso(url){
            $('#editar').load(url, function(){
                $(this).modal('show');
            })
        }
    </script>
{% endblock script %}